{% set name = "aurora" %}
{% set version = "0.6.1" %}
{% set python_min = "3.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aurora-{{ version }}.tar.gz
  sha256: bf0136fb13702f312f70572bf9c08657ee7a4205f4aaf8d496018a7d00f73e26

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - pytest-runner
    - python {{ python_min }}
    - xarray >=2024.10.0
  run:
    - matplotlib-base
    - mt-metadata
    - mth5
    - numba
    - numpy
    - obspy
    - pandas
    - psutil
    - python >={{ python_min }}
    - scipy
    - xarray >=2024.10.0

test:
  imports:
    - aurora
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
    - xarray >=2024.10.0

about:
  home: https://github.com/simpeg/aurora
  summary: Processing Codes for Magnetotelluric Data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kkappler
    - kujaku11
    - lheagy
